# Konfiguracja do pluginu Kubolowe-Gamemode
# Autor pluginu Kubolowe
# Dostepne zmienne {GAMEMODE} {PLAYER}

# Gdzie ma byc wysłana wiadomosc
chat: true
actionbar: true
title: true

# Wiadomosci

no_found_player: "&cNie znaleziono gracza"


chat_message: "&8⮕ &7Zmieniono tryb gry na {GAMEMODE} &8⬅"
chat_message_other: "&8⮕ &7Zmieniono tryb gry na {GAMEMODE} &7przez &#ffd321{PLAYER}&8⬅"
chat_message_other_sender: "&8⮕ &7Zmieniono tryb gry &#ffd321{PLAYER} &7na {GAMEMODE}&8⬅"

actionbar_message: "&8⮕ &7Zmieniono tryb gry na {GAMEMODE} &8⬅"
actionbar_message_other: "&8⮕ &7Zmieniono tryb gry na {GAMEMODE} &7przez &#ffd321{PLAYER}&8⬅"

title_message: "&#ffcd03&lGAMEMODE"
title_desc_message: "&8⮕ &7Zmieniono tryb gry na {GAMEMODE} &8⬅"
title_desc_message_other: "&8⮕ &7Zmieniono tryb gry na {GAMEMODE} &7przez &#ffd321{PLAYER} &8⬅"
fadein: 15
stay: 30
fadeout: 15

# Zmienne
variables:
  survival: "&#ffd321Survival"
  creative: "&#ffd321Kreatywny"
  adventure: "&#ffd321Przygodowy"
  spectator: "&#ffd321Obserwator"
