name: KuboloweCore
version: '1.0'
main: org.kubolowe.kubolowegamemode.Kubolowe_Gamemode
api-version: '1.20'
commands:
  gamemode:
    permission: kubolowe-gamemode
    aliases:
      - gm
  agamemode:
    permission: kubolowe-gamemode